#!/bin/sh
# docker build --build-arg HADOOP_VERSION=2.6.5 --build-arg SPARK_VERSION=2.1.3 -t $IMAGE_NAME .
docker build -t $IMAGE_NAME:latest .

docker build --build-arg HADOOP_VERSION=2.6.5 --build-arg SPARK_VERSION=2.1.3 -t $IMAGE_NAME:spark2.1.3_2.6.5 .
