#!/bin/sh
# docker build --build-arg HADOOP_VERSION=2.6.5 --build-arg SPARK_VERSION=2.1.3 -t $IMAGE_NAME .
docker build --build-arg HADOOP_VERSION=2.8.5 --build-arg SPARK_VERSION=2.4.0 -t $IMAGE_NAME .

docker build --build-arg HADOOP_VERSION=2.6.5 --build-arg SPARK_VERSION=2.1.3 -t ${IMAGE_NAME%latest}spark2.1.3_2.6.5 .
